import matplotlib.pyplot as plt
import matplotlib.patches as mpatches
import numpy as np

from run_experiments import import_mapf_instance
from map_gen import MapGenerator
from matplotlib import colors


def map_vis(map_name: str, num_agents: int = 0) -> None:
    """
        Create illustrations of the various test case maps

    :param map_name:    {str}   name of the map, the path will automatically be adapted based of if
                                instance maps are provided or assignment maps.
    
    :param num_agents:  {int}   number of agents to be spawned within the map.
    """
    if "assignment" in map_name:
        my_map, agents_start, agents_end = MapGenerator(f"maps/{map_name}.map").generate(num_agents)
    else:
        my_map, agents_start, agents_end = import_mapf_instance(f"instances/{map_name}.txt")

    my_map = np.array(my_map)

    cmap = colors.ListedColormap(['#D4D4D4', '#333333'])

    fig, ax = plt.subplots()
    ax.imshow(my_map, cmap=cmap)

    ## Colors generated by ChatGPT on 15-4-2024
    color_pallete = [
        '#1f77b4',  # Blue
        '#ff7f0e',  # Orange
        '#2ca02c',  # Green
        '#d62728',  # Red
        '#9467bd',  # Purple
        '#8c564b',  # Brown
        '#e377c2',  # Pink
        '#bcbd22',  # Olive
        '#17becf',  # Teal
        '#1f78b4',  # Dark Blue
        '#ff7f0f',  # Dark Orange
        '#2da02c',  # Dark Green
        '#d62729',  # Dark Red
        '#9467be',  # Dark Purple
        '#8c564c',  # Dark Brown
        '#e377c3',  # Light Pink
        '#7f7f7e',  # Light Gray
        '#bcbe22',  # Light Olive
        '#17becd',  # Light Teal
    ]

    ## Add agents

    agent = 0

    for agent_start, agent_end in zip(agents_start, agents_end):
        agent += 1

        start = plt.Circle(agent_start[::-1], 0.3, facecolor=color_pallete[agent - 1], edgecolor="k")
        end = mpatches.Rectangle([el - 0.4 for el in agent_end[::-1]], 0.8, 0.8, linewidth=1,
                                 edgecolor=color_pallete[agent - 1], facecolor='none')

        ax.add_patch(start)
        ax.add_patch(end)
        ax.annotate(agent, agent_start[::-1], color='w', weight='bold',
                    fontsize=7, ha='center', va='center')

    plt.axis('off')

    plt.savefig(f'figures/{map_name}.pdf', bbox_inches='tight')

    plt.close()


# for i in range(1, 51):
#     print(f"=== Generating map visualisation of map {i} ===")
#     map_vis(f'test_{i}')

# map_vis("assignment_3")
